### ISSUE TITLE
Better email templates

### ISSUE THREAD

**Issue by davidascher** [mozilla/f1#1]
The emails that get sent out are pretty bare-bones, and I suspect we could make them friendlier without making them obnoxious.

**Comment by clarkbw** [comment]
we should use the person's name in both the <b>to</b> and the <b>from</b> headers so it looks more like the email a person would send.

**Comment by clarkbw** [comment]
We have email templates with db50e37c075454f3f17d41804fb57b9658afc508  however it's tough to define them as "better" :)

Also we have names for the "from" field now.  To get the "to" fields working we'll just need to send the full email addresses in the "to" line.

**Comment by clarkbw** [comment]
A slightly improved template has landed 7e048708e5bd9647857b7c862d12ea8b79a8ecc8 and Andy is improving that even more so I'm going to close this.
