### ISSUE TITLE
navigator share api not injected?

### ISSUE THREAD

**Issue by PatrickG** [mozilla/f1#134]
Hi,

i've installed the F1-Addon from AMO to check a script that running on my website which should open the F1-Panel by clicking on a share-button at the homepage, but the navigator.mozilla object is not injected, even after restarting firefox.

**Comment by clarkbw** [comment]
Hi  -

We're currently not injecting the navigator API into the window.  We had to put that piece on hold for a little while but might bring it back later.  I'll try to update the documentation.

Thanks,
~ Bryan
