### ISSUE TITLE
Support for status.net/identi.ca

### ISSUE THREAD

**Issue by mcepl** [mozilla/f1#135]
As a proponent of the open web, I would love to support open web apps. Could we have support for identi.ca (status.net)? It uses Twitter API anyway.

**Comment by clarkbw** [comment]
The latest development code is here: https://github.com/mozilla/fx-share-addon/

This new development is using the Open Web Apps framework which would allow identi.ca / status.net to implement the twitter or their own API and offer the account install/setup directly to users.

I'm going to close this, thanks for the comment and take a look at the new code and Open Web Apps framework if you're interested in trying to develop the account system.  OWA: https://github.com/mozilla/openwebapps
