### ISSUE TITLE
after reinstalling plugin, oauth window for previously configured accounts remains blank.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/f1#136]
The oauth window remains blank, but the previously configured account is added in the background.

steps to reproduce (my best guess):
1) Install F1
2) Add Twitter and Facebook accounts
3) Remove F1
4) restart
5) Install F1 again.
6) Try to re-add twitter. Twitter acocunt is added, but OAuth screen remains blank.

**Comment by mixedpuppy** [comment]
what f1 addon are you using?  this, or fx-share-addon?

**Comment by shane-tomlinson** [comment]
@mixedpuppy - 0.8.3 from amo.  Strangely enough, an uninstall and re-install a second time did not have me re-enter my account information.
