### ISSUE TITLE
noscript breaks f1

### ISSUE THREAD

**Issue by mixedpuppy** [mozilla/f1#16]
a report from facebook:

Just a quick report, which you might have heard before. Noscript stops your application from working. I.e unless i allow mozillamessaging in no script app refuses to work. and since its not really on page. so users dont even get msg that mozillamessaging is being blocked.

**Comment by Dee-III** [comment]
Thanks for posting it here. 

I have no idea what detail should i give. Anyway <a href="http://lh3.ggpht.com/_VYfxp_7BHoI/TOQy_KRK1ZI/AAAAAAAAAXs/jc0ZzEaH_iM/s640/before.png">here</a> is how it looks before allowing. Normally no-script gives alert that it is blocking scripts. but doesn't gives in this case. And after i go to mozillamessaging and allow it, app works just <a href="http://lh5.ggpht.com/_VYfxp_7BHoI/TOQy_fgrXDI/AAAAAAAAAXw/_ZNbn0MiJxA/s640/after.png">fine</a>. loads normally etc. 

and judging by the comments <a href="https://addons.mozilla.org/en-US/firefox/addon/252539/reviews/254563/">here</a>, I am not the only one facing this issue.

**Comment by jrburke** [comment]
Fixed in [this commit](https://github.com/mozilla/f1/commit/dc32117d593c31ede4ff068ec875df39e8b5a566), add an error message, and indicate what needs to be enabled to enable F1.
