### ISSUE TITLE
sharing youtube video with facebook isn't playable

### ISSUE THREAD

**Issue by clarkbw** [mozilla/f1#17]
A request from the [feedback forums](http://feedback.mozillalabs.com/forums/68185-messaging-add-ons/suggestions/1216865-sharing-youtube-video?ref=title).  We should figure out what is needed to make these come across as real videos since I believe we have that information in the add-on.

**Comment by lhirlimann** [comment]
This is also true on vimeo videos.

**Comment by clarkbw** [comment]
I've got a version of this working in a feature branch but James and Shane should probably look it over before we land it.

I'm most worried about the fragile client code, the changes to the backend are fairly succinct.

Here's the commit: 2b4cebaac233e80598702d7ff94475502749f580

**Comment by clarkbw** [comment]
fixed in this commit: 34902f50c4c902d546a04cfdadfe10bb81d1e79e
