### ISSUE TITLE
disable button if on a non-shareable url

### ISSUE THREAD

**Issue by davidascher** [mozilla/f1#2]
or otherwise make it so that clicking the button while looking at about:home isn't such a WTF?

**Comment by lhirlimann** [comment]
STR :
1) open Firefox's add-on manager
2) click on the f1 button

Expected results :
Nice error message saying we can't really share that page.

Result :
No feedback, f1 button seems like something not useable.

**Comment by clarkbw** [comment]
In d44b5f14ed2db138f7ccd1338e21a5300865dd45 we've made the button disabled on links that you cannot share.  Some additional feedback could be a good thing but this fixes things for now.

**Comment by lhirlimann** [comment]
Bryan today I can't reproduce my STRs.
