### ISSUE TITLE
facebook profile error

### ISSUE THREAD

**Issue by mixedpuppy** [mozilla/f1#21]
<pre>

[Thu Nov 18 07:17:10 2010] [error] Traceback (most recent call last):
[Thu Nov 18 07:17:10 2010] [error]   File "/home/linkdrop/linkdrop/linkdrop/controllers/account.py", line 120, in verify
[Thu Nov 18 07:17:10 2010] [error]     user = auth.verify()
[Thu Nov 18 07:17:10 2010] [error]   File "/home/linkdrop/linkdrop/linkdrop/lib/oauth/base.py", line 145, in verify
[Thu Nov 18 07:17:10 2010] [error]     return self._get_credentials(access_token)
[Thu Nov 18 07:17:10 2010] [error]   File "/home/linkdrop/linkdrop/linkdrop/lib/oauth/facebook_.py", line 152, in _get_credentials
[Thu Nov 18 07:17:10 2010] [error]     profile = extract_fb_data(fb_profile)
[Thu Nov 18 07:17:10 2010] [error]   File "/home/linkdrop/linkdrop/linkdrop/lib/oauth/facebook_.py", line 82, in extract_fb_data
[Thu Nov 18 07:17:10 2010] [error]     'identifier': 'https://graph.facebook.com/%s' % data['id'],
[Thu Nov 18 07:17:10 2010] [error] KeyError: 'id'

</pre>

**Comment by clarkbw** [comment]
moved to server: share: https://bugzilla.mozilla.org/show_bug.cgi?id=642925
