### ISSUE TITLE
Let me tag my friends and use auto completion

### ISSUE THREAD

**Issue by lhirlimann** [mozilla/f1#23]
I would like to be able to tag my friends using @username , I just don't always remember how FB or twiter know my friends. I usually use the proposed auto-completion list to find the proper nickname, would be nice to be able to do that in F1 too.

**Comment by mixedpuppy** [comment]
I'm not clear about what is being asked for.

**Comment by lhirlimann** [comment]
This is half solved. I was asking for name autocompletion.

**Comment by mixedpuppy** [comment]
still not clear.  what is the unsolved half?

**Comment by lhirlimann** [comment]
Half because you implemented it - but last time I tried it didn't work. I think James was working on fixing the case for which it didn't work. issue can be closed.
