### ISSUE TITLE
F1 doesn't work if the page has an empty title node

### ISSUE THREAD

**Issue by sunshowers** [mozilla/f1#24]
i.e. something like

```
<html>
  <head>
    <title></title>
  </head>
  ...
```

The problem is at https://github.com/mozilla/f1/blob/develop/extensions/firefox-share/src/chrome/content/overlay.js#L461 -- for an empty title node firstChild would be undefined.

**Comment by jrburke** [comment]
Fixed in [this commit](https://github.com/mozilla/f1/commit/7ca6280f996112744dc188e57ec7f0bf31631998)
