### ISSUE TITLE
improve the account tooltips

### ISSUE THREAD

**Issue by clarkbw** [mozilla/f1#28]
the tooltips for accounts in the share page hover over the to entry for email systems and because they are click targets for changing account can cause inadvertant switches.

We either need to move the tooltips to a different location or make then non-click targets so they don't take you to that page with accidentally clicked.

**Comment by andychung** [comment]
hrm, the tooltips shouldn't appear unless you're hovering a button though right? I think it's only if you make a very specific mouse movement over the tooltip that it remains visible...

**Comment by clarkbw** [comment]
Right, if you're hovering over Yahoo and then move your mouse left then down you'll get the tooltip for Gmail hovering over the input.  And then clicking the tooltip by accident instead of in the input causes you to change services.  This happened to Shane a couple of times already so I imagine it's happening to more people as well.

I think if the tooltips weren't click actions (or they disappear on click) we would solve this problem.  However this might be an issue that we say is solved by a different version of the UI instead of trying to change the tooltips.  Depends on how easy it is to create a fix.

**Comment by clarkbw** [comment]
With the new UI this is going away.  Closing!
