### ISSUE TITLE
Can't switch dictionaries in the input field

### ISSUE THREAD

**Issue by lhirlimann** [mozilla/f1#3]
Use case :
I want to twit in french. And I'm a very bad speller (I very often misstype words).
STR :
1) go to a page
2) open F1's bar
3) choose say twitter
4) Type some french :"ie cette page est vraiment superbe, je la recomande fortement"
5) Right click in the field to switch dictionnary

Expected results, the usual right click menu show up and I can switch my dictionary, and get rid of all that underlying red.

Results nothing happens. Error console is empty. using 0.7.1 version of the addon with Mozilla/5.0 (Macintosh; Intel Mac OS X 10.5; rv:2.0b6) Gecko/20100101 Firefox/4.0b6.

**Comment by clarkbw** [comment]
Added the context menu attribute so spell check and other context menu items work as of 06361721bbdb4b1226c1cb2bd4cea9db4eb68928

**Comment by lhirlimann** [comment]
Does that mean we need a new release or is that on the hosted part ?

**Comment by clarkbw** [comment]
Yes, this will require a new release of the add-on
