### ISSUE TITLE
bump maxVersion to 4.0b9pre

### ISSUE THREAD

**Issue by clarkbw** [mozilla/f1#31]
This was already done in code ( 7f4c45dfd0decafb28b2cf021df3bf8345560451 ) but we can just bump up the maxVersion compat inside AMO so F1 continues to work with the latest Minefield nightly.  I don't think this even takes an approval.

**Comment by jrburke** [comment]
I just changed this on AMO, it said changes may take a couple of hours to change, so we should check in a couple of hours then close out the ticket.

**Comment by clarkbw** [comment]
Looks like the change worked.  Thanks!
