### ISSUE TITLE
better connecting dialog

### ISSUE THREAD

**Issue by clarkbw** [mozilla/f1#32]
Karen just had a (re-)connecting dialog that never closed.  It looked like it was stuck on the connecting to f1.mozillamessaging.com (according to the status bar) and the page was blank at that moment.  Oh how I wish we didn't have these dialogs...

I'm wondering if we do some simple improvements.
- A simple change would be to add some text to the connecting spinner letting people know they can close the window and try again if it takes too long.
- Perhaps we could watch the dialog from with in the extension or frame page and offer to try again if it's taking too long.

**Comment by davidascher** [comment]
Which connection is that?  is it w/ the third party service?  Could we not assume that it'll work, move it to a serverside queue, and deal with failures as exceptions ("sorry to interrupt, but the tweet you sent last time couldn't go through, we'll keep trying?")

**Comment by clarkbw** [comment]
This is the sign in / re-connect to your account.  If you're already logged into the service and have already approved F1 then this dialog just appears and then disappears.  But sometimes it seems to get stuck.

AFAIK this needs to set a client side cookie.  Though I would really like to do these in a hidden window / background call and only open the dialog if it was prompting the user for something.

**Comment by clarkbw** [comment]
Added to the planning wiki page for future improvements.  With the local OAuth changes this shouldn't be as much of a problem now.
