### ISSUE TITLE
DM UI/UX needs to be fixed

### ISSUE THREAD

**Issue by andychung** [mozilla/f1#40]
The current direct message UI is confusing, need to implement a drop down of some sort that lets the user know where they are sending their message.

**Comment by andychung** [comment]
Refer to Bryan's design for a dropdown + text

**Comment by andychung** [comment]
Here is the desired flow for the "to" field. http://cl.ly/40iw

**Comment by clarkbw** [comment]
James made this happen in 6355030528f6f97bc14aacec0878f36906b7ca84

There is some polish and cleanup to be done but this is fixed.
