### ISSUE TITLE
use the toolbar button for sharing activity

### ISSUE THREAD

**Issue by clarkbw** [mozilla/f1#41]
Currently we overlay the share page with share activity but with the new panel (which takes up more space and is over the page) we should move to a model where the panel removes itself (animates up toward the button) when share is clicked and the share button then animates the sharing progress.

For errors and issues during sharing we can change the button to an error state and pop the panel back down and display a notification bar above the share page with the error information.

**Comment by mixedpuppy** [comment]
done
