### ISSUE TITLE
Constantly being logged out

### ISSUE THREAD

**Issue by andychung** [mozilla/f1#47]
I'm constantly being logged out of my accounts, probably every 10 minutes.

**Comment by mixedpuppy** [comment]
is this on dev or on staging?

**Comment by mkurde** [comment]
I am getting logged out after every restart of my Firefox Beta 4/11. F1 0.7.5
I have to re-add the services before I can start sharing links

**Comment by clarkbw** [comment]
Is this still an issue you're seeing?

**Comment by mixedpuppy** [comment]
no responses, closing, new oauth store should prevent this from happening.

**Comment by mkurde** [comment]
yes its still the same problem

**Comment by mixedpuppy** [comment]
hansp, do you clear cookies on shutdown or anything like that?

**Comment by mkurde** [comment]
yes, i do that. how can i set a rule for F1 to keep the cookie. i useed cookiesafe in FF3, but now it have no cookie addon anymore that can handle this.. cookiesafe is not compatible anymore.

**Comment by mixedpuppy** [comment]
Clearing cookies also clears localstorage, which is where f1 keeps account information, so when you clear cookies, you reset everything in f1.  I'm not sure what addons would be a replacement for cookiesafe.

**Comment by mkurde** [comment]
OK, i need to add a exception to prevent the cookie from deletion. which site i have to enter in the config?

**Comment by mixedpuppy** [comment]
f1.mozillamessaging.com is the site the data is stored for.

**Comment by mkurde** [comment]
ok, it works now. thx
