### ISSUE TITLE
f1 thinks it goofed up when service returns a 'normal' error.

### ISSUE THREAD

**Issue by mhammond** [mozilla/f1#50]
Share something via twitter, then share the exact same thing again.  Twitter responds with a 'status is a duplicate' error, but F1 renders 'We're really sorry, F1 done goofed up. Status is a duplicate.' and an ERROR record is logged.  This should probably be handled slightly more gracefully, telling the user it was twitter which failed rather than f1, and probably with just an INFO log record.

(Note: I see this when testing the share page directly - you should get the same error using it "for real", assuming we get back the same shortened URL the second time.)

**Comment by mixedpuppy** [comment]
fixed...and "Status is duplicate" is passed through to the error dialog.
