### ISSUE TITLE
<select> form controls unusable in the new floating panel

### ISSUE THREAD

**Issue by protz** [mozilla/f1#53]
As this is kind of hard to explain, I recorded a video that's available here http://jonathan.protzenko.free.fr/bugf1.mpg . What happens is:
- when the panel pops up, I'm trying to open a &lt;select> but it never pops up
- I then move the mouse cursor to the right of the panel (this is my desktop) and move it back to the floating panel
- the &lt;select> works,
- I move the mouse cursor to the left of the panel, into the firefox main area, and move it back to the floating panel,
- the &lt;select> doesn't work anymore.

I'm not sure whether this is a gecko bug or a f1 bug, which is why I'm pinging you beforehand.

**Comment by jrburke** [comment]
I confirmed the issue, using Ubuntu, seems to be a Linux only issue.

Clicking on the dropdown for my wall/group wall does not show the list of options. Using the arrow keys allows changing of the value, but the mouse clicks do not open up the dropdown with the list of options.

I expect it is a problem with the browser element being in a panel thing we hit with Firefox 3.6 Windows, but just a different variant of it on Linux.

**Comment by protz** [comment]
I'll try to ping NeilAway on IRC, don't know if he's the one who actually did the panel work, or the other Neil, but I'll try. Thanks for confirming. Might be a Gecko bug...

**Comment by mixedpuppy** [comment]
fixed
