### ISSUE TITLE
error connecting to yahoo

### ISSUE THREAD

**Issue by mhammond** [mozilla/f1#58]
After connecting F1 to my yahoo account, I saw the error shown below.  Strangely though, F1 thinks I can correctly connected - ie, the account is shown - however, attempting to use it then fails with the second traceback below (which is nearly identical to the first).  Note I see these exact same errors in the production logs, so it isn't "just me" :)

Traceback when connecting the account:

<pre>
12:47:18,973 ERROR [linkdrop.lib.helpers] [worker 8] <function get at 0x037EB130>((<linkdrop.control
lers.contacts.ContactsController object at 0x03804770>, u'yahoo.com'), {}) failed
Traceback (most recent call last):
  File "O:\src\mm\f1\work\linkdrop\lib\helpers.py", line 128, in json_exception_response
    return func(*args, **kwargs)
  File "O:\src\mm\f1\work\linkdrop\controllers\contacts.py", line 122, in get
    result, error = provider.api(acct).getcontacts(startIndex, maxResults, group)
  File "O:\src\mm\f1\work\linkdrop\lib\oauth\yahoo_.py", line 118, in __init__
    self.oauth_token = oauth.Token(key=account.get('oauth_token'), secret=account.get('oauth_token_secret'))
  File "o:\src\python-2.6-svn\lib\site-packages\oauth2-1.2.0-py2.6.egg\oauth2\__init__.py", line 167, in __init__
    raise ValueError("Key and secret must be set.")
ValueError: Key and secret must be set.
</pre>

Traceback attempting to send:

<pre>
12:47:18,990 INFO  [linkdrop-metrics] [worker 8] function='get' id='unhandled-exception' when=1298857638.99 remote_address='127.0.0.1' error='ValueError'
12:50:16,559 ERROR [linkdrop.controllers.send] [worker 6] error providing item to yahoo.com: Key and secret must be set.
Traceback (most recent call last):
  File "O:\src\mm\f1\work\linkdrop\controllers\send.py", line 175, in send
    result, error = provider.api(acct).sendmessage(message, args)
  File "O:\src\mm\f1\work\linkdrop\lib\oauth\yahoo_.py", line 118, in __init__
    self.oauth_token = oauth.Token(key=account.get('oauth_token'), secret=account.get('oauth_token_secret'))
  File "o:\src\python-2.6-svn\lib\site-packages\oauth2-1.2.0-py2.6.egg\oauth2\__init__.py", line 167, in __init__
    raise ValueError("Key and secret must be set.")
ValueError: Key and secret must be set.
12:50:16,582 INFO  [linkdrop-metrics] [worker 6] domain='yahoo.com' short_url=None when=1298857816.5
810001 remote_address='127.0.0.1' message_len=3 took=0.022459279042550406 acct_id='82e74acdfccfefd8ce6ae0011f3b2350ae956338' long_url='http://twitter.com/' error={'status': 401, 'message': 'not logged in or no user account for that domain', 'provider': u'yahoo.com'} id='send-error'
</pre>

**Comment by mhammond** [comment]
FWIW, this "Key and secret must be set" is by far the most common exception in the production logs.

**Comment by mixedpuppy** [comment]
This error is caused by oauth tokens being absent from the account data.  It is caught and turned into a 401 for the front end, but the exception is logged.  I cant see how the tokens could be missing with the latest changes.  I assumed it was some loss of session data before.

**Comment by clarkbw** [comment]
moved to: https://bugzilla.mozilla.org/show_bug.cgi?id=642911
