### ISSUE TITLE
error fetching contacts from linkedin

### ISSUE THREAD

**Issue by mhammond** [mozilla/f1#59]
From the production logs - it appears linkedin may return null if there are no contacts rather than an empty list:

<pre>
[Wed Feb 23 08:11:42 2011] [error] 08:11:42,201 ERROR [linkdrop.lib.helpers] [Dummy-2] <function get at 0x2aaab16aa2a8>((<linkdrop.controllers.contacts.ContactsController object at 0x2aaab14a3c50>, u'linkedin.com'), {}) failed
[Wed Feb 23 08:11:42 2011] [error] Traceback (most recent call last):
[Wed Feb 23 08:11:42 2011] [error]   File "/home/linkdrop/linkdrop/linkdrop/lib/helpers.py", line 120, in json_exception_response
[Wed Feb 23 08:11:42 2011] [error]     return func(*args, **kwargs)
[Wed Feb 23 08:11:42 2011] [error]   File "/home/linkdrop/linkdrop/linkdrop/controllers/contacts.py", line 122, in get
[Wed Feb 23 08:11:42 2011] [error]     result, error = provider.api(acct).getcontacts(startIndex, maxResults, group)
[Wed Feb 23 08:11:42 2011] [error]   File "/home/linkdrop/linkdrop/linkdrop/lib/oauth/linkedin_.py", line 180, in getcontacts
[Wed Feb 23 08:11:42 2011] [error]     for entry in entries:
[Wed Feb 23 08:11:42 2011] [error] TypeError: 'NoneType' object is not iterable

</pre>

**Comment by mixedpuppy** [comment]
fixed
