### ISSUE TITLE
Facebook errors sharing certain URLs

### ISSUE THREAD

**Issue by mhammond** [mozilla/f1#63]
Found via production logs and reproduced locally.  Use F1 to share:

http://www.theregister.co.uk/2002/11/13/gates_gives_100m_to_fight/

Facebook responds with:

<pre>
error={'status': 400, u'message': u'(#100) picture URL is not properly formatted', 'code': 0, u'type': u'OAuthException', 'provider': 'facebook.com'}
</pre>

For some reason there has been a bit of a spike in this error on Monday - over 25, whereas every other day has < 10, even though the total number of shares and users is roughly the same.

**Comment by mixedpuppy** [comment]
Facebook is checking that we are giving it a canonical url, which we werent.  This probably caused image failures on other services unless they did the canonical verification.

fixed.

**Comment by mixedpuppy** [comment]
this was a problem in the extension itself, the fix will provided with an update to the extension.
