### ISSUE TITLE
andy: inconsistent identity / branding

### ISSUE THREAD

**Issue by clarkbw** [mozilla/f1#64]
We're using a combination of styles of F1 in various places and we need to have some consistency in our form.

toolbar icon: f1
website: icon = _F1_, title = F1 by Mozilla Labs, copy = So, what's F1?, etc.
panel: heading = Mozilla F1, footer = Latest from F1 team
settings: icon = _F1_, heading = F1 Configuration, title = F1: Config

The lowercase version of the toolbar button looks pretty good but without some kind of typographical design work to make it stand out it blends in too much with the other text.  We need some identity guidelines for when to use what and where.

**Comment by andychung** [comment]
What would you say to re-doing our branding a little bit? The F1 icon was made in a bit of a rush after having to ship with a last minute name change from Linkdrop?

**Comment by clarkbw** [comment]
Lets see some prototypes!

**Comment by clarkbw** [comment]
Fixed the inconsistency issues in a478c3a7a846e4edcbd48f1ee17f90808c0f13c5

Andy is going to continue working on the identity and that is listed in the Planning wiki page.
