### ISSUE TITLE
bit.ly settings won't get stored

### ISSUE THREAD

**Issue by mkurde** [mozilla/f1#67]
When I enter my bit.ly name and key and hit save the page returns to the main config page. When I return to the advanced tab, the bit.ly checkbox is not checked and all data i enterd id gone
[https://f1.mozillamessaging.com/0.2.7/setting....]

2nd note: the HTML code for the bit.ly checkbox is wrong
Bad:
input id="bitlyCheckbox" type="checkbox"> <label for="bitly"

Good:
input id="bitly" type="checkbox"> <label for="bitly"
the id of label and input id should be the same. If so you can click the label to tick the checkbox...  ;)

**Comment by jrburke** [comment]
I just fixed the label issue. 

As far as saving the info, are you using a privacy add-on like Better Privacy? I believe it blocks localStorage/DOM Storage use in web pages, and that would explain the error. 

If that is the issue, we are considering a longer term fix, perhaps pushing the data into chrome space for storage, but that will come later.

**Comment by mkurde** [comment]
Yes I use BetterPrivacy. How can I make a rule for F1 in BetterPrivacy?

**Comment by jrburke** [comment]
If there is an option to allow f1.mozillamessaging.com to use DOM storage, that will do the trick, but I am not sure what the exact incantation is for BetterPrivacy.
