### ISSUE TITLE
figure out how to communicate changes & important info in F1 to the user

### ISSUE THREAD

**Issue by davidascher** [mozilla/f1#7]
In particular, changes to the service, planned downtime, etc., but also changes in functionality in the client, where to configure eventual settings, etc.

**Comment by clarkbw** [comment]
We have a "new" text now that can be used to actually display any text we want and will remain for a couple days.  I think we should use this and updates to the settings page to communicate issues to users.

**Comment by clarkbw** [comment]
Added this to the planning wiki but closing out since this is a meta bug and not an actionable issue.
