### ISSUE TITLE
Google Reader/Buzz Support

### ISSUE THREAD

**Issue by d3x7r0** [mozilla/f1#71]
I think the title is pretty self-explanatory: I wonder if it would be possible to add an option to share in google reader (and that google buzz thingy I don't actually use).

**Comment by clarkbw** [comment]
Thanks for the suggestion!  We have Google Reader support in our planning wiki and I guess I could add Buzz as well. :)  Before we add many more services we're working on ways to be extensible to lots of different services by providing a simple developer API to create new services.  We might just get Google Reader support added before that work but GR was slated to be one of our "extensible services".

Thanks!

**Comment by d3x7r0** [comment]
Glad to know that. I just suggested it here cause I couldn't find much info on the project itself (maybe due to my subpar searching skills) and since google reader has been so far my method of choice for content sharing.
