### ISSUE TITLE
sharing flash on facebook failures

### ISSUE THREAD

**Issue by mixedpuppy** [mozilla/f1#73]
A number of failures on facebook, with a good error message for a change:

long_url='http://rasteri.blogspot.com/2011/03/chain-of-fools-upgrading-through-every.html' error={'status': 400, u'message': u"(#100) flash objects must have the 'swfsrc' and 'imgsrc' attributes", 'code': 0, u'type': u'OAuthException', 'provider': 'facebook.com'}

**Comment by jrburke** [comment]
Fix issue where sharing a video requires a picture preview. Had logic for it, but was in the wrong place. Closed by e2dd2e2f05d5ba8c1fac57156dc83d5a5ba7941a
