### ISSUE TITLE
repeat 401 errors

### ISSUE THREAD

**Issue by mixedpuppy** [mozilla/f1#77]
It seems some people are repeatedly trying to re-share a url and getting 401s, we need to test the error result and make sure the ui is handling it properly.  We can force a 401 response and see the ui handling of it, but it's hard to know if in the real world something strange is happening (e.g. is the user re-auth-ing several times or not).  Something to think about in the test harness.

long_url='http://downloadsquad.switched.com/2011/03/10/how-to-customize-exactly-what-appears-in-your-facebook-news-feed/' error={'status': 401, u'message': u'Error validating access token.', 'code': 0, u'type': u'OAuthException', 'provider': 'facebook.com'}

**Comment by clarkbw** [comment]
moved to: https://bugzilla.mozilla.org/show_bug.cgi?id=642914
