### ISSUE TITLE
fancybox?

### ISSUE THREAD

**Issue by mixedpuppy** [mozilla/f1#78]
I see a few of these errors:

[Sat Mar 12 08:12:48 2011] [error] [client 24.2.234.243] File does not exist: /home/linkdrop/linkdrop/web/current/fancybox

We do have fancybox in there, perhaps there is an incorrect link somewhere in the code.

**Comment by jrburke** [comment]
Some IE-specific css rules for fancybox had bad paths. Closed by 0ce18b8ba34c5eabb61cbe6a080f4311be1de884
