### ISSUE TITLE
facebook connectino errors

### ISSUE THREAD

**Issue by mixedpuppy** [mozilla/f1#80]
We're not handling connection errors in some places for facebook...

[Fri Mar 11 15:04:31 2011] [error] Traceback (most recent call last):

[Fri Mar 11 15:04:31 2011] [error]   File "/home/linkdrop/linkdrop/linkdrop/lib/helpers.py", line 128, in json_exception_response

[Fri Mar 11 15:04:31 2011] [error]     return func(_args, *_kwargs)

[Fri Mar 11 15:04:31 2011] [error]   File "/home/linkdrop/linkdrop/linkdrop/controllers/contacts.py", line 127, in get

[Fri Mar 11 15:04:31 2011] [error]     result, error = provider.api(acct).getcontacts(startIndex, maxResults, group)

[Fri Mar 11 15:04:31 2011] [error]   File "/home/linkdrop/linkdrop/linkdrop/lib/oauth/facebook_.py", line 274, in getcontacts

[Fri Mar 11 15:04:31 2011] [error]     result, error = self.rawcall(url)

[Fri Mar 11 15:04:31 2011] [error]   File "/home/linkdrop/linkdrop/linkdrop/lib/oauth/facebook_.py", line 223, in rawcall

[Fri Mar 11 15:04:31 2011] [error]     resp, content = httplib2.Http().request(url, method=method, headers=headers, body=body)

[Fri Mar 11 15:04:31 2011] [error]   File "build/bdist.linux-x86_64/egg/httplib2/**init**.py", line 1129, in request

[Fri Mar 11 15:04:31 2011] [error](response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)

[Fri Mar 11 15:04:31 2011] [error]   File "build/bdist.linux-x86_64/egg/httplib2/**init**.py", line 901, in _request

[Fri Mar 11 15:04:31 2011] [error](response, content) = self._conn_request(conn, request_uri, method, body, headers)

[Fri Mar 11 15:04:31 2011] [error]   File "build/bdist.linux-x86_64/egg/httplib2/**init**.py", line 871, in _conn_request

[Fri Mar 11 15:04:31 2011] [error]     response = conn.getresponse()

[Fri Mar 11 15:04:31 2011] [error]   File "/usr/lib64/python2.6/httplib.py", line 986, in getresponse

[Fri Mar 11 15:04:31 2011] [error]     response.begin()

[Fri Mar 11 15:04:31 2011] [error]   File "/usr/lib64/python2.6/httplib.py", line 391, in begin

[Fri Mar 11 15:04:31 2011] [error]     version, status, reason = self._read_status()

[Fri Mar 11 15:04:31 2011] [error]   File "/usr/lib64/python2.6/httplib.py", line 349, in _read_status

[Fri Mar 11 15:04:31 2011] [error]     line = self.fp.readline()

[Fri Mar 11 15:04:31 2011] [error]   File "/usr/lib64/python2.6/socket.py", line 397, in readline

[Fri Mar 11 15:04:31 2011] [error]     data = recv(1)

[Fri Mar 11 15:04:31 2011] [error]   File "/usr/lib64/python2.6/ssl.py", line 96, in <lambda>

[Fri Mar 11 15:04:31 2011] [error]     self.recv = lambda buflen=1024, flags=0: SSLSocket.recv(self, buflen, flags)

[Fri Mar 11 15:04:31 2011] [error]   File "/usr/lib64/python2.6/ssl.py", line 217, in recv

[Fri Mar 11 15:04:31 2011] [error]     return self.read(buflen)

[Fri Mar 11 15:04:31 2011] [error]   File "/usr/lib64/python2.6/ssl.py", line 136, in read

[Fri Mar 11 15:04:31 2011] [error]     return self._sslobj.read(len)

[Fri Mar 11 15:04:31 2011] [error] error: [Errno 104] Connection reset by peer

[Fri Mar 11 15:04:31 2011] [error] 15:04:31,215 INFO  [linkdrop-metrics] [Dummy-1] function='get' id='unhandled-exception' when=1299884671.2150631 remote_address='151.68.179.215' error='error'

[Fri Mar 11 15:04:47 2011] [error] 15:04:47,274 ERROR [linkdrop.controllers.account] [Dummy-2] failed to verify the facebook.com account

[Fri Mar 11 15:04:47 2011] [error] Traceback (most recent call last):

[Fri Mar 11 15:04:47 2011] [error]   File "/home/linkdrop/linkdrop/linkdrop/controllers/account.py", line 119, in verify

[Fri Mar 11 15:04:47 2011] [error]     user = auth.verify()

[Fri Mar 11 15:04:47 2011] [error]   File "/home/linkdrop/linkdrop/linkdrop/lib/oauth/base.py", line 153, in verify

[Fri Mar 11 15:04:47 2011] [error]     return self._get_credentials(access_token)

[Fri Mar 11 15:04:47 2011] [error]   File "/home/linkdrop/linkdrop/linkdrop/lib/oauth/facebook_.py", line 147, in _get_credentials

[Fri Mar 11 15:04:47 2011] [error]     resp, content = client.request(url(profile_url, access_token=access_token, fields=fields))

[Fri Mar 11 15:04:47 2011] [error]   File "build/bdist.linux-x86_64/egg/httplib2/**init**.py", line 1129, in request

[Fri Mar 11 15:04:47 2011] [error](response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)

[Fri Mar 11 15:04:47 2011] [error]   File "build/bdist.linux-x86_64/egg/httplib2/**init**.py", line 901, in _request

[Fri Mar 11 15:04:47 2011] [error](response, content) = self._conn_request(conn, request_uri, method, body, headers)

[Fri Mar 11 15:04:47 2011] [error]   File "build/bdist.linux-x86_64/egg/httplib2/**init**.py", line 871, in _conn_request

[Fri Mar 11 15:04:47 2011] [error]     response = conn.getresponse()

[Fri Mar 11 15:04:47 2011] [error]   File "/usr/lib64/python2.6/httplib.py", line 986, in getresponse

[Fri Mar 11 15:04:47 2011] [error]     response.begin()

[Fri Mar 11 15:04:47 2011] [error]   File "/usr/lib64/python2.6/httplib.py", line 391, in begin

[Fri Mar 11 15:04:47 2011] [error]     version, status, reason = self._read_status()

[Fri Mar 11 15:04:47 2011] [error]   File "/usr/lib64/python2.6/httplib.py", line 349, in _read_status

[Fri Mar 11 15:04:47 2011] [error]     line = self.fp.readline()

[Fri Mar 11 15:04:47 2011] [error]   File "/usr/lib64/python2.6/socket.py", line 397, in readline

[Fri Mar 11 15:04:47 2011] [error]     data = recv(1)

[Fri Mar 11 15:04:47 2011] [error]   File "/usr/lib64/python2.6/ssl.py", line 96, in <lambda>

[Fri Mar 11 15:04:47 2011] [error]     self.recv = lambda buflen=1024, flags=0: SSLSocket.recv(self, buflen, flags)

[Fri Mar 11 15:04:47 2011] [error]   File "/usr/lib64/python2.6/ssl.py", line 217, in recv

[Fri Mar 11 15:04:47 2011] [error]     return self.read(buflen)

[Fri Mar 11 15:04:47 2011] [error]   File "/usr/lib64/python2.6/ssl.py", line 136, in read

[Fri Mar 11 15:04:47 2011] [error]     return self._sslobj.read(len)

[Fri Mar 11 15:04:47 2011] [error] error: [Errno 104] Connection reset by peer

**Comment by clarkbw** [comment]
moved to: https://bugzilla.mozilla.org/show_bug.cgi?id=642909
