### ISSUE TITLE
Status.Net, OExchange, etc support

### ISSUE THREAD

**Issue by johndrinkwater** [mozilla/f1#82]
Mozilla seem to have forgotten their own goals in only supporting certain sites (3rd party client hating twitter, data loving facebook) rather than APIs and platforms for the Open Web… Please fix that.

**Comment by mixedpuppy** [comment]
In reality, we are looking at extensibility from several perspectives, including oexchange for which there is a working branch in this repository.  Oexchange is not ideal for our goals, and implementing components for each api does not scale.  Likely we'll be doing something around the openwebapps project to provide extensibility by 3rd parties.
