### ISSUE TITLE
sharing a facebook page to facebook

### ISSUE THREAD

**Issue by mixedpuppy** [mozilla/f1#84]
You cannot share stuff that is in fbcn.net to facebook

[Sun Mar 13 20:16:41 2011] [error] 20:16:41,242 INFO  [linkdrop-metrics] [Dummy-1] domain='facebook.com' short_url=None when=1300072601.24227 remote_address='xxx' message_len=12 took=0.0 acct_id='xxx' long_url='http://video.l3.fbcdn.net/cfs-l3-snc6/81489/34/1605260179420_2624.mp4?oh=ac31b4d8738221641ba490396dc19636&oe=4D7F9F00&l3s=20110313100648&l3e=20110315101648&lh=0a6cfa5eeaecd6dc12abf' error={'status': 400, u'message': u'(#100) FBCDN image is not allowed in stream: http://video.l3.fbcdn.net/cfs-l3-snc6/81489/34/1605260179420_2624.mp4?oh=ac31b4d8738221641ba490396dc19636&oe=4D7F9F00&l3s=20110313100648&l3e=20110315101648&lh=0a6cfa5eeaecd6dc12abf', 'code': 0, u'type': u'OAuthException', 'provider': 'facebook.com'} id='send-error'

**Comment by clarkbw** [comment]
moved to server: share; https://bugzilla.mozilla.org/show_bug.cgi?id=642927
