### ISSUE TITLE
GMail user photo missing

### ISSUE THREAD

**Issue by clarkbw** [mozilla/f1#86]
I have a photo set for my GMail account and I haven't seen my F1 update to use that photo, I'm wondering if we're not returning it correctly.  Anyone else seeing their photo in the GMail tab?

**Comment by mixedpuppy** [comment]
google doesn't provide it to us in the openid+oauth results.  I also do not see a 'profile' api for gmail accounts to ask for it...

**Comment by clarkbw** [comment]
Oh, I thought it was part of the contacts API call.

http://code.google.com/apis/contacts/docs/2.0/developers_guide_protocol.html#retrieving_photo

**Comment by clarkbw** [comment]
moved to: https://bugzilla.mozilla.org/show_bug.cgi?id=642907
