### ISSUE TITLE
Facebook occasionally complains "URL is not properly formatted"

### ISSUE THREAD

**Issue by mhammond** [mozilla/f1#90]
Attempt to share: http://www.the-requiem.cz.cc/2011/03/east-jesus-nowhere.html

Facebook's response:

<pre>
5:17:50,615 INFO  [linkdrop-metrics] [worker 1] domain='facebook.com' short_url=None when=130033547.6159999 remote_address='127.0.0.1' message_len=5 took=1.0033934480499624 acct_id='xxx' long_url='http://www.the-requiem.cz.cc/2011/03/east-jesus-nowhere.html' eror={'status': 400, u'message': u'(#100) link URL is not properly formatted', 'code': 0, u'type': u'AuthException', 'provider': 'facebook.com'} id='send-error'
</pre>

The above seems reproducible (ie, was not transient).  Ditto for the ftp site listed below (but the http version of that mozilla page shares OK)

Other URLs in the log with the same error:

<pre>
http://www.noroeste.com.mx/publicaciones.php?id=669120
ftp://ftp.mozilla.org/pub/mozilla.org/firefox/nightly/4.0rc1-candidates/build1/win32/en-US/
http://apptrackr.org/?act=viewapp&appid=351733272
http://www.alzalam.tk/vb/showthread.php?t=235
file:///C:/Documents%20and%20Settings/Mecanifoz/Ambiente%20de%20trabalho/comissaoaooo.html (heh!)
</pre>

**Comment by davidascher** [comment]
iiuc, these are all fine URLs that just trip up facebook's url detector?  we should likely file them downstream...

**Comment by mhammond** [comment]
Not sure what you mean by "fine URL" but looking a little deeper:

http://www.the-requiem.cz.cc/2011/03/east-jesus-nowhere.html returns a 404 but with text/html content (Firefox shows it fine)

The rest of the http:// URLs all seem normal - they give 200 responses and a text/html content-type.

Agreed we should filter out ftp:// and file:// schemes, but we probably just want a whitelist of schemes we do support.

**Comment by clarkbw** [comment]
moved to: https://bugzilla.mozilla.org/show_bug.cgi?id=642905
