### ISSUE TITLE
error in panel.js: generateBase64Preview

### ISSUE THREAD

**Issue by clarkbw** [mozilla/f1#92]
generateBase64Preview: [Exception... "Component is not available"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://ffshare/modules/panel.js :: <TOP_LEVEL> :: line 462"  data: no]

seeing this error on command line dump

**Comment by philikon** [comment]
Fixed: https://github.com/mozilla/f1/commit/4f78cf8793853bccfb725b0737090e4081992e90
