### ISSUE TITLE
dump error: installFFShareIntoWindow Reference Error

### ISSUE THREAD

**Issue by clarkbw** [mozilla/f1#95]
I'm seeing this error dumped to console on startup.  

load error ReferenceError: installFFShareIntoWindow is not defined

Looks  like it's referencing this line: https://github.com/mozilla/f1/blob/develop/extensions/firefox-share/src/bootstrap.js#L49

**Comment by philikon** [comment]
Well, the function is defined here: https://github.com/mozilla/f1/blob/develop/extensions/firefox-share/src/modules/main.js#L49

Maybe you have some caching going on?

**Comment by clarkbw** [comment]
I double checked the caching but if no one else is seeing this then it must just be me.

**Comment by mixedpuppy** [comment]
all the code is moved into modules.  if you're using the filepath method of installing the addon, you may have to enable/disable the addon, or worse, try to delete extensions.\* files in the profile and restart to get modifications of the modules to load.

**Comment by clarkbw** [comment]
ok, uninstalled and reinstalled - things seems to work correctly now.
